server:
  port: 80
spring:
  application:
    name: cloud-consumer-80
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      # connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
payMent:
  # url: http://localhost:8001/
  server: http://cloud-payment-server/


