server:
  port: 83

spring:
  application:
    name: nacos-Order-Server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'

payMent:
  server: http://nacosServer/