server:
  port: 83

spring:
  application:
    name: nacos-Order-Server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.129:1111  #nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'

payMent:
  server: http://nacos-provider/