server:
  port: 9527

spring:
  application:
    name: cloud-gateway9257
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能  利用微服务名称进行路由
      routes:
        - id: PayMent_route1  #路由id 没有固定的命名要求 建议配合服务名
          #   uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER #匹配后提供服务的路由地址
          predicates:
            - Path=/PayMent/** #断言 路径相同进行路由
          #  - After=2020-07-30T22:32:12.725+08:00[Asia/Shanghai] #在这个时间之后才生效
        #   - Cookie=username,md
        #   - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达书

        - id: PayMent_route2  #路由id 没有固定的命名要求 建议配合服务名
          #    uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/PayMent/getServerInfo/** #断言 路径相同进行路由
            - After=2020-07-30T22:32:12.725+08:00[Asia/Shanghai] #在这个时间之后才生效
            # - Cookie=username,md

eureka:
  client:
    #将自己注入eureka
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #访问路径显示IP地址
    prefer-ip-address: true
    instance-id: cloud-gateway9257
    #eureka客户端向服务端发送心跳时间间隔  默认30秒
    lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳后的等待时间上限 默认90秒  超时剔除服务
    lease-expiration-duration-in-seconds: 30



