server:
  port: 8401

spring:
  application:
    name: sentinel-8401
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos地址
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        #默认8719地址  如果被占用  从8719依次往后面+1扫描
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: '*'