server:
  port: 8002

spring:
  application:
    name: cloud-payment-server
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率 0-1之间 1代表全部采集
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cfx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: a5268413

#logging:
#  level: info
#  file:
#    path: classpath/log.log
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.md.springcloud.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    #将自己注入eureka
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: payment8002
    #eureka客户端向服务端发送心跳时间间隔  默认30秒
    lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳后的等待时间上限 默认90秒  超时剔除服务
    lease-expiration-duration-in-seconds: 30