server:
  port: 9001

spring:
  application:
    name: nacosServer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'