server:
  port: 80

payMent:
  url: http://localhost:8001/

eureka:
  client:
    #将自己注入eureka
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

