server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.129:1111  #nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'