server:
  port: 80
spring:
  application:
    name: cloud-consumer-80
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率 0-1之间 1代表全部采集
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}
payMent:
  # url: http://localhost:8001/
  server: http://cloud-payment-server/


